// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaAuEif4VIeSKsM5ENWvar_AKGqHjegi4',
    appId: '1:356706532497:android:0f1deb2d2008326fa4d330',
    messagingSenderId: '356706532497',
    projectId: 'trackingapp-b11b6',
    databaseURL: 'https://trackingapp-b11b6-default-rtdb.firebaseio.com',
    storageBucket: 'trackingapp-b11b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF1Jq6FMrDJ-YBwyIuZSpuF_8pn2MO5Ro',
    appId: '1:356706532497:ios:16ea11b0afe40229a4d330',
    messagingSenderId: '356706532497',
    projectId: 'trackingapp-b11b6',
    databaseURL: 'https://trackingapp-b11b6-default-rtdb.firebaseio.com',
    storageBucket: 'trackingapp-b11b6.firebasestorage.app',
    iosBundleId: 'com.example.trackingApp',
  );
}
